const bar  = (score) => '█'.repeat(Math.round(score / 10)) + '░'.repeat(10 - Math.round(score / 10));
const grade = (g) => ({ 'A+': '🟢', A: '🟢', B: '🔵', C: '🟡', D: '🟠', F: '🔴' }[g] ?? '⚪');

const dimSection = (label, dim) => {
    if (!dim) return '';
    const lines = [
        `## ${label} — ${grade(dim.grade)} ${dim.grade} (${dim.score}/100)`,
        '',
        `\`${bar(dim.score)}\``,
        '',
    ];
    if (dim.evidence?.length)  lines.push('**Found:** ' + dim.evidence.join(' · '), '');
    if (dim.missing?.length)   lines.push('**Missing:** ' + dim.missing.join(' · '), '');
    if (dim.notes)             lines.push('> ' + dim.notes, '');
    return lines.join('\n');
};

/**
 * Generates SCORE.md markdown from a repo analysis object.
 *
 * @param {string} repoName
 * @param {object} analysis  Result of analyzeRepo()
 */
export const generateScoreReport = (repoName, analysis) => {
    const { codeQuality, suggestions, techStack, meta } = analysis;
    const date = new Date().toISOString().slice(0, 10);
    const { testing, documentation, tooling, ci, security, structure } = codeQuality;

    const dims = [
        ['Testing',       testing],
        ['Documentation', documentation],
        ['Tooling',       tooling],
        ['CI/CD',         ci],
        ['Security',      security],
        ['Structure',     structure],
    ];

    const table = [
        '| Dimension | Score | Grade |',
        '|---|:---:|:---:|',
        ...dims.map(([label, d]) => `| ${label} | ${d?.score ?? '—'}/100 | ${d?.grade ?? '—'} |`),
    ].join('\n');

    const parts = [
        `# Code Quality Report — \`${repoName}\``,
        `_Generated ${date} · ${meta?.language || 'unknown language'}_`,
        '',
        `## Overall Grade: ${grade(codeQuality.grade)} ${codeQuality.grade} (${codeQuality.overall}/100)`,
        '',
        `\`${bar(codeQuality.overall)}\``,
        '',
        table,
        '',
        '---',
        '',
        ...dims.map(([label, d]) => dimSection(label, d) + '\n---\n'),
    ];

    if (suggestions?.length) {
        parts.push('## Suggestions', '');
        suggestions.forEach((s, i) => parts.push(`${i + 1}. ${s}`));
        parts.push('');
    }

    if (techStack?.length) {
        parts.push('## Tech Stack Detected', '');
        parts.push(techStack.map(t => `\`${t}\``).join(' · '), '');
    }

    parts.push('---');
    parts.push('_Generated by [github-pretty-readme](https://github.com/kevinthelago/github-pretty-readme)_');

    return parts.join('\n');
};

/**
 * Generates a README.md from a scan's readmeOutline.
 *
 * @param {string} repoName
 * @param {object} analysis  Result of analyzeRepo()
 */
export const generateReadmeFromOutline = (repoName, analysis) => {
    const { readmeOutline, techStack, meta } = analysis;
    if (!readmeOutline) return null;

    const { title, tagline, features, installationSteps, usageExample } = readmeOutline;
    const parts = [];

    parts.push(`# ${title || repoName}`, '');
    if (tagline) parts.push(`> ${tagline}`, '');

    if (meta?.language) {
        parts.push(`![${meta.language}](https://img.shields.io/badge/-${encodeURIComponent(meta.language)}-555?style=flat)`);
    }
    if (meta?.license) {
        parts.push(`![License](https://img.shields.io/badge/license-${encodeURIComponent(meta.license)}-blue?style=flat)`);
    }
    if (meta?.language || meta?.license) parts.push('');

    if (features?.length) {
        parts.push('## Features', '');
        features.forEach(f => parts.push(`- ${f}`));
        parts.push('');
    }

    if (installationSteps?.length) {
        parts.push('## Installation', '');
        parts.push('```bash');
        installationSteps.forEach(s => parts.push(s));
        parts.push('```', '');
    }

    if (usageExample) {
        parts.push('## Usage', '');
        parts.push('```');
        parts.push(usageExample);
        parts.push('```', '');
    }

    if (techStack?.length) {
        parts.push('## Built With', '');
        parts.push(techStack.map(t => `- ${t}`).join('\n'), '');
    }

    if (meta?.license) {
        parts.push('## License', '');
        parts.push(`[${meta.license}](LICENSE)`, '');
    }

    return parts.join('\n');
};
