// The code-quality badge lives with the README generator; re-exported here so
// SCORE.md consumers can keep importing it from this module unchanged.
export { scoreBadgeMd } from './repo-readme.js';

const bar  = (score) => '█'.repeat(Math.round(score / 10)) + '░'.repeat(10 - Math.round(score / 10));
const grade = (g) => ({ 'A+': '🟢', A: '🟢', B: '🔵', C: '🟡', D: '🟠', F: '🔴' }[g] ?? '⚪');

const dimSection = (label, dim) => {
    if (!dim) return '';
    const lines = [
        `## ${label} — ${grade(dim.grade)} ${dim.grade} (${dim.score}/100)`,
        '',
        `\`${bar(dim.score)}\``,
        '',
    ];
    if (dim.evidence?.length)  lines.push('**Found:** ' + dim.evidence.join(' · '), '');
    if (dim.missing?.length)   lines.push('**Missing:** ' + dim.missing.join(' · '), '');
    if (dim.notes)             lines.push('> ' + dim.notes, '');
    return lines.join('\n');
};

/**
 * Generates SCORE.md markdown from a repo analysis object.
 *
 * @param {string} repoName
 * @param {object} analysis  Result of analyzeRepo()
 */
export const generateScoreReport = (repoName, analysis) => {
    const { codeQuality, suggestions, techStack, meta } = analysis;
    const date = new Date().toISOString().slice(0, 10);
    const { testing, documentation, tooling, ci, security, structure } = codeQuality;

    const dims = [
        ['Testing',       testing],
        ['Documentation', documentation],
        ['Tooling',       tooling],
        ['CI/CD',         ci],
        ['Security',      security],
        ['Structure',     structure],
    ];

    const table = [
        '| Dimension | Score | Grade |',
        '|---|:---:|:---:|',
        ...dims.map(([label, d]) => `| ${label} | ${d?.score ?? '—'}/100 | ${d?.grade ?? '—'} |`),
    ].join('\n');

    const parts = [
        `# Code Quality Report — \`${repoName}\``,
        `_Generated ${date} · ${meta?.language || 'unknown language'}_`,
        '',
        `## Overall Grade: ${grade(codeQuality.grade)} ${codeQuality.grade} (${codeQuality.overall}/100)`,
        '',
        `\`${bar(codeQuality.overall)}\``,
        '',
        table,
        '',
        '---',
        '',
        ...dims.map(([label, d]) => dimSection(label, d) + '\n---\n'),
    ];

    if (suggestions?.length) {
        parts.push('## Suggestions', '');
        suggestions.forEach((s, i) => parts.push(`${i + 1}. ${s}`));
        parts.push('');
    }

    if (techStack?.length) {
        parts.push('## Tech Stack Detected', '');
        parts.push(techStack.map(t => `\`${t}\``).join(' · '), '');
    }

    parts.push('---');
    parts.push('_Generated by [github-pretty-readme](https://github.com/kevinthelago/github-pretty-readme)_');

    return parts.join('\n');
};
